algoritmo "Teste laco para"
// Função :
// Autor :
// Data : 27/03/2015
// Seção de Declarações 
var
    i : inteiro
    r : real
    t : caractere
inicio
  t <- "a" + "v"

  para i de 10 ate 1 passo 0 faca
    escreva(i)
  fimpara
  para i de 1 ate 10 faca
     r <- 0
  fimpara
  escreva(i)
  
  para i de 1 ate 10 faca
    escreval(i)
    i <- i * 2
  fimpara
fimalgoritmo
